plugins {
    id 'com.android.application'
}

android {
    namespace 'app.thien.tracker'
    compileSdk 36
    defaultConfig {
        applicationId "app.thien.tracker"
        minSdk 24
        targetSdk 36
        versionCode 200
        versionName "BT.GG.HT 1.0"
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
